name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # Pour OIDC
      contents: read       # Pour checkout

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_AWS_ROLE }}
          aws-region: ca-central-1

      - name: Install dependencies
        run: npm ci

      - name: Build the frontend
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_REGION: ca-central-1
          AWS_S3_BUCKET: anhk  # Remplace si ton bucket a un nom différent
          SOURCE_DIR: client/dist
